/**
 * Ghost Vessel semantics (GFST) — frontend.
 *
 * The designation, the warning and the hypothesis/unknown vocabularies are
 * generated by the backend and served in the evidence document, so there is
 * exactly ONE authority for this language. They are mirrored here only as a
 * fallback for the brief window before evidence loads, and a test asserts the
 * two agree.
 *
 * Nothing in this file infers intent. The hypotheses are all about observation —
 * coverage, staleness, propagation, detection — because intent is not measurable
 * from a radar return plus an absent association.
 */

/** The analytical class. Product-facing wording never replaces it. */
export const GHOST_CLASSIFICATION = 'SAR_UNMATCHED';

/** Rendered ABOVE the analytical class. */
export const GHOST_LABEL = 'GHOST VESSEL';

/** Shown on every Ghost Vessel surface, undismissable. */
export const GHOST_WARNING =
  'No sufficiently confident AIS association was found in the available observations ' +
  'and correlation window. This alone does not establish why.';

/**
 * Phrases that must never appear in product copy for a Ghost Vessel.
 *
 * A backend test asserts the emitted strings are clean; this list is the
 * frontend's half of the same gate.
 */
export const FORBIDDEN_INFERENCES: readonly string[] = [
  'transponder intentionally disabled',
  'transponder disabled',
  'ais was never transmitted',
  'dark vessel',
  'sanctions',
  'smuggling',
  'criminal',
  'hostile',
  'deceptive',
  'concealment',
  'illegal fishing',
  'military intent',
  'no transponder',
  'go dark',
];

export const HYPOTHESES: readonly string[] = [
  'AIS coverage gap: no receiver covered this position at acquisition time.',
  'Stale observation: the nearest AIS report was too old to associate.',
  'The vessel was not broadcasting a position report at that moment.',
  'The vessel was outside reliable reception for its class and heading.',
  'The return is not a vessel: surface clutter, a structure, or a processing artefact that met the detection threshold.',
  'Incidence angle or radar geometry degraded detectability or association.',
];

export const UNKNOWNS: readonly string[] = [
  'Identity',
  'Flag or registry',
  'Destination',
  'Cargo',
  'Intent',
  'Whether any AIS transmission exists at all',
  'Whether the vessel is crewed',
  'Whether the return is a vessel at all',
];

export function isGhostVessel(classification: unknown): boolean {
  return String(classification) === GHOST_CLASSIFICATION;
}